### ISSUE TITLE
Como ver o resultado final do Mundo Gelado

### ISSUE THREAD

**Issue by raqcalazans** [reprograma/On5-responsivo#33]
Eei Bah, boa tarde! Vi agora que vc aprovou o merge da minha tarefa de casa... Obrigada! 

Queria saber se consigo ver o resultado em alguma url que o github fornece. 

Att, Raquel Calazans

**Comment by barbara-aguilar** [comment]
Oi Raquel, como os exercícios das alunas todas estão nesse repo não consigo gerar um githubpages. Mas uma coisa bacana que você pode fazer é abrir um repo no seu github colar a resolução lá html e css, depois de subir pra master o github permite renderizar em uma url do github pages e pode usar já para seu portfolio.
Nesse link você vai aprender o passo a passo. https://help.github.com/pt/github/working-with-github-pages/getting-started-with-github-pages

**Comment by raqcalazans** [comment]
Tá bem Bah! Vou fazer isso... Obrigada por responder! :)
